# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trivia',
            new_name='Score',
        ),
    ]
